version: 2.1


jobs:
  saluda:
    machine: 
      - image: ubuntu-2204:20.10.2
    steps:
      - run: echo hola 

workflows:
  workflow1: # this can be any name you choose
    jobs:
      - saluda
          

