version: 2.1
orbs:
  probely: probely/security-scan@1.1.3

workflows:
  example-workflow:
    jobs:
      - probely/scan:
          target_id: $PROBELY_TARGET_ID
          context: dast


        

          
