version: 2.1
orbs:
  slack: usertech/circleci-slack-orb@5.1.0
jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "deploy my app"
      - slack/notify:
          event: fail
          template: default_fail_1
      - slack/notify:
          event: pass
          template: default_pass_1
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "test my app"
workflows:
  test-and-deploy:
    jobs:
      - test
      - slack/on-hold:
          context: SLACK_SECRETS
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
      - pause_workflow:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
            - slack/on-hold
          type: approval
      - deploy:
          filters:
            tags:
              only: /^v.*/
          requires:
            - pause_workflow
