version 2.1
jobs:
  saluda: # this can be any name you choose
    docker: 
      - image cimg/base:stable # use the default executor defined within the orb
    steps:
      - run: echo hola
workflows:
  hello: # this can be any name you choose
    jobs: 
      - saluda # use the default executor defined within the orb
         
