version: 2.1
orbs:
  deepfactor: deepfactor/deepfactor@1.2.0
workflows:
  build:
    jobs:
      - deepfactor/scan:
          app-name: circleci-demo-job
          cmd: /usr/local/bin/npm test
          component-name: circleci-demo-javascript-express
          portal-url: https://yourdeepfactor.yourcompany.com
          pre-run:
            - checkout
            - run:
                command: node -v
                name: check-node-version
            - run:
                command: npm install
                name: update-npm
          tag: circleci-build
  version: 2.1
