version: 2.1

orbs:
  snyk: snyk/snyk@2.0.1

jobs:
 build:
   docker:
     - image: circleci/node:4.8.2
   steps:
     - checkout
     - snyk/install
     - run:
          name: List Files
          command: pwd
     - run:
          name: Run code scan
          command: snyk code test
          

workflows:
  version: 2
  test:
    jobs:
      - build:
          context: snyk