version: 2.1
jobs:
  saluda: # this can be any name you choose
    docker: 
      - image: cimg/base:stable 
    steps:
      - run: echo hola
  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo pre adios
      - run: echo adios
      - run: echo post adios
workflows:
  workflows1:
    hello: # this can be any name you choose
      jobs: 
        - saluda
        - despidete
  workflows2:
    hello: # this can be any name you choose
      jobs: 
        - saluda
        - despidete:
            requires:
              - saluda
