version: 2.1
orbs:
  node: circleci/node@5.1
  slack: usertech/circleci-slack-orb@5.1.0
jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy
      - slack/notify:
          channel: ABCXYZ
          event: fail
          template: default_fail_1
workflows:
  deploy_and_notify:
    jobs:
      - deploy:
          context: SLACK_SECRETS

