version: 2.1
orbs:
  probely: probely/security-scan@1.1.3

jobs:
  my_probely_scan:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install jq
          command: |
            sudo apt-get update && sudo apt-get install -y jq
      - run:
          name: Get scans
          command: |
            curl -X GET "https://api.eu.probely.com/targets/39orRp99KgFc/scans/" \
            -H "Authorization: JWT $PROBELY_API_KEY" \
            -o scans.json
      - run:
          name: Print scans.json
          command: cat scans.json
      - run:
          name: Extract last scan ID
          command: |
            ID_VALUE=$(jq -r '.results[0].id' scans.json)
            echo "ID Value: $ID_VALUE"
      - run:
          name: Download Probely scan results
          command: |
            REPORT_URL="https://api.eu.probely.com/targets/$PROBELY_TARGET_ID/scans/$ID_VALUE/report/?report_type=default"
            echo "URL del informe: $REPORT_URL"
            curl -X GET "$REPORT_URL" \
            -H "Authorization: JWT $PROBELY_API_KEY" \
            -o probely-report.pdf
               
      - store_artifacts:
          path: probely-report.pdf
          destination: scan-results

          
workflows:
  version: 2
  example-workflow:
    jobs:
      - my_probely_scan:
          context: dast

        

          
