version: 2.1
orbs:
  probely: probely/security-scan@1.1.3

jobs:
  my_probely_scan:
    docker:
      - image: cimg/base:stable
    steps:
      
      - run:
          name: Wait for scan results
          command: sleep 3 # wait for 5 minutes
      - run:
          name: Download Probely scan results
          command: |
            curl -X GET "https://api.eu.probely.com/targets/39orRp99KgFc/scans/3DJdjguzSv6A/report/?report_type=default" \
            -H "Authorization: JWT $PROBELY_API_KEY" \
            -o probely-report.json
      - store_artifacts:
          path: probely-report.json
          destination: scan-results

          
workflows:
  version: 2
  example-workflow:
    jobs:
      - my_probely_scan:
          context: dast

        

          
