version: 2.1
orbs:
  probely: probely/security-scan@1.1.3
      

jobs:
 build:
   docker:
     - image: circleci/node:4.8.2
   steps:
     - run:
          command: echo PROBELY_TARGET_ID

workflows:
  example-workflow:
    jobs:
      - probely/scan:
          target_id: PROBELY_TARGET_ID
          context: dast
      - build:
          context: dast

        

          
