version: 2.1


jobs:
  saluda:
    docker: 
      - image: ubuntu:latest 
    steps:
      - run: echo hola 

workflows:
  workflow1: # this can be any name you choose
    jobs:
      - saluda
          

