version: 2.1

orbs:
  snyk: snyk/snyk@2.0.1

jobs:
 build:
   docker:
     - image: circleci/node:4.8.2
   steps:
     - run:
          name: List Files
          command: ls
     - checkout
     - snyk/scan

workflows:
  version: 2
  test:
    jobs:
      - build:
          context: snyk