version: 2.1


jobs:
  saluda:
    parameters:
      nombre:
        type: string
        default: guof
    docker: 
      - image: cimg/base:stable 
    steps:
      - run: echo hola << pipeline.parameters.nombre>>

workflows:
  workflow1: # this can be any name you choose
    jobs: 
      - saluda

  workflow2:
    jobs:
      - saluda:
          nombre: chomchito
        